import type { Analysis, ClassifiedTest } from './types';
import { fmtMs, verdictLabel } from './plain-english';

export interface SummaryOptions {
  /** TestRelic dashboard URL to link to, if known. */
  dashboardUrl?: string | null;
}

/**
 * Produces the headline verdict — the single most important line. This is what
 * lands in a Slack message or a PR comment; everything else is detail.
 */
export function headline(a: Analysis): string {
  const bugs = a.newBugs.length + a.persistentBugs.length;
  if (bugs === 0 && a.flaky === 0 && a.flakyTests.length === 0) {
    return `🟢 All ${a.total} tests passed${a.runsInHistory ? ` — and clean across the last ${a.runsInHistory} runs` : ''}.`;
  }
  const parts: string[] = [];
  if (a.newBugs.length) parts.push(`🔴 ${a.newBugs.length} new failure${plural(a.newBugs.length)} that look${a.newBugs.length === 1 ? 's' : ''} like a real bug`);
  if (a.persistentBugs.length) parts.push(`🟠 ${a.persistentBugs.length} still broken`);
  const flakyCount = a.flakyTests.length;
  if (flakyCount) parts.push(`🟡 ${flakyCount} flaky (noise)`);
  parts.push(`✅ ${a.passed} passed`);
  return parts.join(' · ');
}

/** Plain-text summary for terminals and Slack. */
export function toText(a: Analysis, opts: SummaryOptions = {}): string {
  const L: string[] = [];
  L.push(headline(a));
  L.push('');

  if (a.newBugs.length) {
    L.push('FIX FIRST — new failures that look like real bugs:');
    for (const c of a.newBugs) L.push(...block(c));
    L.push('');
  }
  if (a.persistentBugs.length) {
    L.push('STILL BROKEN — failing across recent runs:');
    for (const c of a.persistentBugs) L.push(...block(c));
    L.push('');
  }
  if (a.flakyTests.length) {
    L.push('FLAKY NOISE — do not block your release on these:');
    for (const c of a.flakyTests) L.push(`  • ${c.test.name} — ${c.plainEnglish}`);
    L.push('');
  }
  if (a.slowRegressions.length) {
    L.push('SLOWING DOWN:');
    for (const c of a.slowRegressions) L.push(`  • ${c.test.name} — ${c.plainEnglish}`);
    L.push('');
  }

  L.push(`Slowest tests this run: ${a.slowest.map((t) => `${shortName(t.name)} (${fmtMs(t.durationMs)})`).join(', ') || '—'}`);
  if (opts.dashboardUrl) L.push(`Full report: ${opts.dashboardUrl}`);
  L.push(`Run ${a.run.runId}${a.run.branch ? ` on ${a.run.branch}` : ''} · history: ${a.runsInHistory} prior run${plural(a.runsInHistory)}`);
  return L.join('\n');
}

function block(c: ClassifiedTest): string[] {
  const lines = [`  • [${verdictLabel(c.verdict)}] ${c.test.name}`, `      ${c.plainEnglish}`];
  if (c.test.failure?.location) lines.push(`      where: ${c.test.failure.location}`);
  lines.push(`      do: ${c.nextStep}`);
  return lines;
}

/** Markdown summary for PR comments / docs / Slack mrkdwn. */
export function toMarkdown(a: Analysis, opts: SummaryOptions = {}): string {
  const M: string[] = [];
  M.push(`## ${headline(a)}`);
  M.push('');
  M.push(`**${a.passed} passed · ${a.failed} failed · ${a.flaky} flaky · ${a.skipped} skipped** out of ${a.total} tests.`);
  M.push('');

  if (a.newBugs.length) {
    M.push('### 🔴 Fix first — new failures that look like real bugs');
    for (const c of a.newBugs) M.push(...mdBlock(c));
  }
  if (a.persistentBugs.length) {
    M.push('### 🟠 Still broken');
    for (const c of a.persistentBugs) M.push(...mdBlock(c));
  }
  if (a.flakyTests.length) {
    M.push('### 🟡 Flaky noise (safe to ignore for now)');
    for (const c of a.flakyTests) M.push(`- **${c.test.name}** — ${c.plainEnglish}`);
    M.push('');
  }
  if (a.slowRegressions.length) {
    M.push('### ⏱️ Slowing down');
    for (const c of a.slowRegressions) M.push(`- **${c.test.name}** — ${c.plainEnglish}`);
    M.push('');
  }

  M.push('---');
  M.push(`Slowest this run: ${a.slowest.map((t) => `\`${shortName(t.name)}\` (${fmtMs(t.durationMs)})`).join(', ') || '—'}.`);
  if (opts.dashboardUrl) M.push(`[View full run in TestRelic →](${opts.dashboardUrl})`);
  M.push('');
  M.push(`<sub>Run \`${a.run.runId}\`${a.run.branch ? ` · ${a.run.branch}` : ''} · compared against ${a.runsInHistory} prior run${plural(a.runsInHistory)} · generated by TestPulse</sub>`);
  return M.join('\n');
}

function mdBlock(c: ClassifiedTest): string[] {
  const lines = [`- **${c.test.name}** — _${verdictLabel(c.verdict)}_`, `  - ${c.plainEnglish}`];
  if (c.test.failure?.location) lines.push(`  - \`${c.test.failure.location}\``);
  lines.push(`  - 👉 ${c.nextStep}`);
  return lines;
}

/** Machine-readable output for CI gating or piping into other tools. */
export function toJson(a: Analysis): string {
  return JSON.stringify(
    {
      headline: headline(a),
      runId: a.run.runId,
      branch: a.run.branch,
      totals: { total: a.total, passed: a.passed, failed: a.failed, flaky: a.flaky, skipped: a.skipped },
      runsInHistory: a.runsInHistory,
      newBugs: a.newBugs.map(serialize),
      persistentBugs: a.persistentBugs.map(serialize),
      flaky: a.flakyTests.map(serialize),
      slowRegressions: a.slowRegressions.map(serialize),
      slowest: a.slowest.map((t) => ({ name: t.name, durationMs: t.durationMs })),
    },
    null,
    2,
  );
}

function serialize(c: ClassifiedTest) {
  return {
    name: c.test.name,
    verdict: c.verdict,
    passRate: Number(c.passRate.toFixed(2)),
    runsConsidered: c.runsConsidered,
    plainEnglish: c.plainEnglish,
    nextStep: c.nextStep,
    location: c.test.failure?.location ?? null,
  };
}

function shortName(name: string): string {
  const parts = name.split('>').map((s) => s.trim());
  return parts[parts.length - 1] || name;
}
function plural(n: number): string {
  return n === 1 ? '' : 's';
}
